---
- name: Setup container for building.
  hosts: localhost
  tasks:
    - name: Create a container
      containers.podman.podman_container:
        name: dev-contain-debian-builder
        image: docker.io/library/debian:bookworm
        volume: "{{ playbook_dir }}:/mnt/dev_contain:Z"
        command: 'sleep infinity'
        state: started
    - name: Add the container to inventory.
      ansible.builtin.add_host:
        name: dev-contain-debian-builder
        ansible_connection: containers.podman.podman
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        changed_when: false
    - name: Set the container up for normal ansible stuff.
      delegate_to: dev-contain-debian-builder
      raw: bash -c "apt update && apt install -y python3"

- name: Setup build environment.
  hosts: dev-contain-debian-builder
  become: true
  tasks:
  - name: Update cache
    ansible.builtin.apt:
      update_cache: true
  - name: Install build dependencies.
    ansible.builtin.apt:
       package:
        - python3-pip
        - python3-setuptools
        - build-essential
        - fakeroot
        - devscripts
        - debhelper
        - dh-python
       state: latest

- name: Build package.
  hosts: dev-contain-debian-builder
  tasks:
  - name: Make out of tree build directory.
    ansible.builtin.tempfile:
      state: directory
      suffix: build
      prefix: dev_contain
    register: temp_file_loc
  - name: Copy build files to location.
    ansible.builtin.shell:
      cmd: "cp -r /mnt/dev_contain {{ temp_file_loc.path }}/. "
  - name: Call debuild.
    ansible.builtin.shell:
       chdir: "{{temp_file_loc.path }}/dev_contain"
       cmd: debuild -us -uc -b
  - name: Copy deb file back to the main directory.
    ansible.builtin.shell:
      cmd: "cp -r  {{ temp_file_loc.path }}/*.deb /mnt/dev_contain/."
  - name: Copy changes file back to the main directory.
    ansible.builtin.shell:
      cmd: "cp -r  {{ temp_file_loc.path }}/*.changes /mnt/dev_contain/."
  - name: Copy buildinfo file back to the main directory.
    ansible.builtin.shell:
      cmd: "cp -r  {{ temp_file_loc.path }}/*.buildinfo /mnt/dev_contain/."

- name: Upload to packaging server.
  hosts: packaging
  tags: deploy
  tasks:
    - name: Copy package to packaging server.
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/public/apt/mini-dinstall/incoming/
      with_fileglob: dev-contain*.deb
      register: copied_files
    - name: Fail if we didn't copy exactly one file.
      ansible.builtin.fail:
        msg: "Didn't find exactly one deb file."
      when: copied_files.results | length != 1
    - name: Ditto the changes file.
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/public/apt/mini-dinstall/incoming/
      with_fileglob: dev-contain*.changes
      register: copied_changes
    - name: Fail if we didn't copy exactly one file.
      ansible.builtin.fail:
        msg: "Didn't find exactly one changes file."
      when: copied_changes.results | length != 1
    - name: Ditto the buildinfo file.
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/public/apt/mini-dinstall/incoming/
      with_fileglob: dev-contain*.buildinfo
      register: copied_buildinfo
    - name: Fail if we didn't copy exactly one file.
      ansible.builtin.fail:
        msg: "Didn't find exactly one buildinfo file."
      when: copied_buildinfo.results | length != 1
    - name: Run mini-dinstall.
      ansible.builtin.shell:
       cmd: "mini-dinstall --batch"

- name: Cleanup
  hosts: localhost
  tags: cleanup
  tasks:
    - name: Stop the container.
      containers.podman.podman_container:
        name: dev-contain-debian-builder
        state: absent